name: Email Step Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 25ds1000058@ds.study.iitm.ac.in
        run: echo "Hello, world! This step contains my email."
