name: CI with Caching

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Cache dependencies
      - name: prime-cache-f1fcb19
        id: cache-deps        # <- this id is used to reference outputs
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-f1fcb19

      # Print cache status
      - name: Show cache hit/miss
        run: echo "Cache hit? ${{ steps.cache-deps.outputs.cache-hit }}"
