name: CI with Caching

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup cache
      - name: prime-cache-f1fcb19
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip   # change this depending on what you want to cache
          key: cache-f1fcb19

      # Step 3: Print cache status
      - name: Cache status
        run: echo "Cache hit? ${{ steps.cache-deps.outputs.cache-hit }}"

      # Step 4: Install dependencies (example: pip)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
